controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



# il est posible de fair une route comme ca
#home:
#    path: /
#    controller: App\Controller\HomeController::index
